name: Deploy_Samples_Website
on:
  push:
    branches: [main]

jobs:
  dispatch:
    name: Dispatch
    env:
      PACKAGES_TO_UPGRADE: ${{ needs.run_publish.outputs.packages }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['needle-tools/needle-engine-samples-web']
    timeout-minutes: 5
    steps:
      - name: Dispatch to workflows
        run: |
            curl -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
            --request POST \
            --data '{"event_type": "deploy_docs", "client_payload": { "reason": "Samples Update: ${{ github.event.head_commit.message }}" }}' https://api.github.com/repos/${{ matrix.repo }}/dispatches